services:

  database:
    container_name: alura_tube_db
    image: postgres:14.5-alpine
    restart: 'no'
    volumes:
      - ../../db/pgdata:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=aluratube
      - POSTGRES_USER=aluratube
    ports:
      - 5435:5432
