services:

  postgres:
    container_name: alura_tube_db
    image: postgres:14.5-alpine
    restart: 'no'
    volumes:
      - ../db/pgdata:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=aluratube
      - POSTGRES_USER=aluratube
    ports:
      - 5435:5432

  nginx:
    container_name: nginx
    image: nginx:1.23.2-alpine
    restart: 'no'
    volumes:
      - /home/henrique/Desenvolvimento/repositorios/pessoal/backend5/docker/nginx/default_local:/etc/nginx/conf.d/default.conf
      - /home/henrique/Desenvolvimento/repositorios/pessoal/backend5/staticfiles:/var/www/site/static
    network_mode: "host"
